/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.org.mars.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Environment extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3416123286838524034L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Environment\",\"namespace\":\"com.org.mars.avro\",\"fields\":[{\"name\":\"temperature\",\"type\":\"double\"},{\"name\":\"windSpeed\",\"type\":\"double\"},{\"name\":\"dustLevel\",\"type\":\"double\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Environment> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Environment> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Environment> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Environment> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Environment> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Environment to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Environment from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Environment instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Environment fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private double temperature;
  private double windSpeed;
  private double dustLevel;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Environment() {}

  /**
   * All-args constructor.
   * @param temperature The new value for temperature
   * @param windSpeed The new value for windSpeed
   * @param dustLevel The new value for dustLevel
   */
  public Environment(java.lang.Double temperature, java.lang.Double windSpeed, java.lang.Double dustLevel) {
    this.temperature = temperature;
    this.windSpeed = windSpeed;
    this.dustLevel = dustLevel;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return temperature;
    case 1: return windSpeed;
    case 2: return dustLevel;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: temperature = (java.lang.Double)value$; break;
    case 1: windSpeed = (java.lang.Double)value$; break;
    case 2: dustLevel = (java.lang.Double)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'temperature' field.
   * @return The value of the 'temperature' field.
   */
  public double getTemperature() {
    return temperature;
  }


  /**
   * Sets the value of the 'temperature' field.
   * @param value the value to set.
   */
  public void setTemperature(double value) {
    this.temperature = value;
  }

  /**
   * Gets the value of the 'windSpeed' field.
   * @return The value of the 'windSpeed' field.
   */
  public double getWindSpeed() {
    return windSpeed;
  }


  /**
   * Sets the value of the 'windSpeed' field.
   * @param value the value to set.
   */
  public void setWindSpeed(double value) {
    this.windSpeed = value;
  }

  /**
   * Gets the value of the 'dustLevel' field.
   * @return The value of the 'dustLevel' field.
   */
  public double getDustLevel() {
    return dustLevel;
  }


  /**
   * Sets the value of the 'dustLevel' field.
   * @param value the value to set.
   */
  public void setDustLevel(double value) {
    this.dustLevel = value;
  }

  /**
   * Creates a new Environment RecordBuilder.
   * @return A new Environment RecordBuilder
   */
  public static com.org.mars.avro.Environment.Builder newBuilder() {
    return new com.org.mars.avro.Environment.Builder();
  }

  /**
   * Creates a new Environment RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Environment RecordBuilder
   */
  public static com.org.mars.avro.Environment.Builder newBuilder(com.org.mars.avro.Environment.Builder other) {
    if (other == null) {
      return new com.org.mars.avro.Environment.Builder();
    } else {
      return new com.org.mars.avro.Environment.Builder(other);
    }
  }

  /**
   * Creates a new Environment RecordBuilder by copying an existing Environment instance.
   * @param other The existing instance to copy.
   * @return A new Environment RecordBuilder
   */
  public static com.org.mars.avro.Environment.Builder newBuilder(com.org.mars.avro.Environment other) {
    if (other == null) {
      return new com.org.mars.avro.Environment.Builder();
    } else {
      return new com.org.mars.avro.Environment.Builder(other);
    }
  }

  /**
   * RecordBuilder for Environment instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Environment>
    implements org.apache.avro.data.RecordBuilder<Environment> {

    private double temperature;
    private double windSpeed;
    private double dustLevel;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.org.mars.avro.Environment.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.temperature)) {
        this.temperature = data().deepCopy(fields()[0].schema(), other.temperature);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.windSpeed)) {
        this.windSpeed = data().deepCopy(fields()[1].schema(), other.windSpeed);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.dustLevel)) {
        this.dustLevel = data().deepCopy(fields()[2].schema(), other.dustLevel);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing Environment instance
     * @param other The existing instance to copy.
     */
    private Builder(com.org.mars.avro.Environment other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.temperature)) {
        this.temperature = data().deepCopy(fields()[0].schema(), other.temperature);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.windSpeed)) {
        this.windSpeed = data().deepCopy(fields()[1].schema(), other.windSpeed);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.dustLevel)) {
        this.dustLevel = data().deepCopy(fields()[2].schema(), other.dustLevel);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'temperature' field.
      * @return The value.
      */
    public double getTemperature() {
      return temperature;
    }


    /**
      * Sets the value of the 'temperature' field.
      * @param value The value of 'temperature'.
      * @return This builder.
      */
    public com.org.mars.avro.Environment.Builder setTemperature(double value) {
      validate(fields()[0], value);
      this.temperature = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'temperature' field has been set.
      * @return True if the 'temperature' field has been set, false otherwise.
      */
    public boolean hasTemperature() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'temperature' field.
      * @return This builder.
      */
    public com.org.mars.avro.Environment.Builder clearTemperature() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'windSpeed' field.
      * @return The value.
      */
    public double getWindSpeed() {
      return windSpeed;
    }


    /**
      * Sets the value of the 'windSpeed' field.
      * @param value The value of 'windSpeed'.
      * @return This builder.
      */
    public com.org.mars.avro.Environment.Builder setWindSpeed(double value) {
      validate(fields()[1], value);
      this.windSpeed = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'windSpeed' field has been set.
      * @return True if the 'windSpeed' field has been set, false otherwise.
      */
    public boolean hasWindSpeed() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'windSpeed' field.
      * @return This builder.
      */
    public com.org.mars.avro.Environment.Builder clearWindSpeed() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'dustLevel' field.
      * @return The value.
      */
    public double getDustLevel() {
      return dustLevel;
    }


    /**
      * Sets the value of the 'dustLevel' field.
      * @param value The value of 'dustLevel'.
      * @return This builder.
      */
    public com.org.mars.avro.Environment.Builder setDustLevel(double value) {
      validate(fields()[2], value);
      this.dustLevel = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'dustLevel' field has been set.
      * @return True if the 'dustLevel' field has been set, false otherwise.
      */
    public boolean hasDustLevel() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'dustLevel' field.
      * @return This builder.
      */
    public com.org.mars.avro.Environment.Builder clearDustLevel() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Environment build() {
      try {
        Environment record = new Environment();
        record.temperature = fieldSetFlags()[0] ? this.temperature : (java.lang.Double) defaultValue(fields()[0]);
        record.windSpeed = fieldSetFlags()[1] ? this.windSpeed : (java.lang.Double) defaultValue(fields()[1]);
        record.dustLevel = fieldSetFlags()[2] ? this.dustLevel : (java.lang.Double) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Environment>
    WRITER$ = (org.apache.avro.io.DatumWriter<Environment>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Environment>
    READER$ = (org.apache.avro.io.DatumReader<Environment>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeDouble(this.temperature);

    out.writeDouble(this.windSpeed);

    out.writeDouble(this.dustLevel);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.temperature = in.readDouble();

      this.windSpeed = in.readDouble();

      this.dustLevel = in.readDouble();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.temperature = in.readDouble();
          break;

        case 1:
          this.windSpeed = in.readDouble();
          break;

        case 2:
          this.dustLevel = in.readDouble();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










