/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.org.mars.avro;
@org.apache.avro.specific.AvroGenerated
public enum PlayerState implements org.apache.avro.generic.GenericEnumSymbol<PlayerState> {
  REGISTER, PLAYER_MOVE, ACTION, PING  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PlayerState\",\"namespace\":\"com.org.mars.avro\",\"symbols\":[\"REGISTER\",\"PLAYER_MOVE\",\"ACTION\",\"PING\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
