/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.org.mars.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class PlayerMoveEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4248538794171603029L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PlayerMoveEvent\",\"namespace\":\"com.org.mars.avro\",\"fields\":[{\"name\":\"messageType\",\"type\":{\"type\":\"enum\",\"name\":\"PlayerState\",\"symbols\":[\"REGISTER\",\"PLAYER_MOVE\",\"ACTION\",\"PING\"]}},{\"name\":\"tick\",\"type\":\"long\"},{\"name\":\"worldTime\",\"type\":\"long\"},{\"name\":\"environment\",\"type\":{\"type\":\"record\",\"name\":\"Environment\",\"fields\":[{\"name\":\"temperature\",\"type\":\"double\"},{\"name\":\"windSpeed\",\"type\":\"double\"},{\"name\":\"dustLevel\",\"type\":\"double\"}]}},{\"name\":\"players\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"record\",\"name\":\"Player\",\"fields\":[{\"name\":\"playerId\",\"type\":\"long\"},{\"name\":\"position\",\"type\":{\"type\":\"record\",\"name\":\"Position\",\"fields\":[{\"name\":\"x\",\"type\":\"double\"},{\"name\":\"y\",\"type\":\"double\"},{\"name\":\"z\",\"type\":\"double\"}]}}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PlayerMoveEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PlayerMoveEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PlayerMoveEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PlayerMoveEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PlayerMoveEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PlayerMoveEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PlayerMoveEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PlayerMoveEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PlayerMoveEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private com.org.mars.avro.PlayerState messageType;
  private long tick;
  private long worldTime;
  private com.org.mars.avro.Environment environment;
  private java.util.Map<java.lang.CharSequence,com.org.mars.avro.Player> players;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PlayerMoveEvent() {}

  /**
   * All-args constructor.
   * @param messageType The new value for messageType
   * @param tick The new value for tick
   * @param worldTime The new value for worldTime
   * @param environment The new value for environment
   * @param players The new value for players
   */
  public PlayerMoveEvent(com.org.mars.avro.PlayerState messageType, java.lang.Long tick, java.lang.Long worldTime, com.org.mars.avro.Environment environment, java.util.Map<java.lang.CharSequence,com.org.mars.avro.Player> players) {
    this.messageType = messageType;
    this.tick = tick;
    this.worldTime = worldTime;
    this.environment = environment;
    this.players = players;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return messageType;
    case 1: return tick;
    case 2: return worldTime;
    case 3: return environment;
    case 4: return players;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: messageType = (com.org.mars.avro.PlayerState)value$; break;
    case 1: tick = (java.lang.Long)value$; break;
    case 2: worldTime = (java.lang.Long)value$; break;
    case 3: environment = (com.org.mars.avro.Environment)value$; break;
    case 4: players = (java.util.Map<java.lang.CharSequence,com.org.mars.avro.Player>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'messageType' field.
   * @return The value of the 'messageType' field.
   */
  public com.org.mars.avro.PlayerState getMessageType() {
    return messageType;
  }


  /**
   * Sets the value of the 'messageType' field.
   * @param value the value to set.
   */
  public void setMessageType(com.org.mars.avro.PlayerState value) {
    this.messageType = value;
  }

  /**
   * Gets the value of the 'tick' field.
   * @return The value of the 'tick' field.
   */
  public long getTick() {
    return tick;
  }


  /**
   * Sets the value of the 'tick' field.
   * @param value the value to set.
   */
  public void setTick(long value) {
    this.tick = value;
  }

  /**
   * Gets the value of the 'worldTime' field.
   * @return The value of the 'worldTime' field.
   */
  public long getWorldTime() {
    return worldTime;
  }


  /**
   * Sets the value of the 'worldTime' field.
   * @param value the value to set.
   */
  public void setWorldTime(long value) {
    this.worldTime = value;
  }

  /**
   * Gets the value of the 'environment' field.
   * @return The value of the 'environment' field.
   */
  public com.org.mars.avro.Environment getEnvironment() {
    return environment;
  }


  /**
   * Sets the value of the 'environment' field.
   * @param value the value to set.
   */
  public void setEnvironment(com.org.mars.avro.Environment value) {
    this.environment = value;
  }

  /**
   * Gets the value of the 'players' field.
   * @return The value of the 'players' field.
   */
  public java.util.Map<java.lang.CharSequence,com.org.mars.avro.Player> getPlayers() {
    return players;
  }


  /**
   * Sets the value of the 'players' field.
   * @param value the value to set.
   */
  public void setPlayers(java.util.Map<java.lang.CharSequence,com.org.mars.avro.Player> value) {
    this.players = value;
  }

  /**
   * Creates a new PlayerMoveEvent RecordBuilder.
   * @return A new PlayerMoveEvent RecordBuilder
   */
  public static com.org.mars.avro.PlayerMoveEvent.Builder newBuilder() {
    return new com.org.mars.avro.PlayerMoveEvent.Builder();
  }

  /**
   * Creates a new PlayerMoveEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PlayerMoveEvent RecordBuilder
   */
  public static com.org.mars.avro.PlayerMoveEvent.Builder newBuilder(com.org.mars.avro.PlayerMoveEvent.Builder other) {
    if (other == null) {
      return new com.org.mars.avro.PlayerMoveEvent.Builder();
    } else {
      return new com.org.mars.avro.PlayerMoveEvent.Builder(other);
    }
  }

  /**
   * Creates a new PlayerMoveEvent RecordBuilder by copying an existing PlayerMoveEvent instance.
   * @param other The existing instance to copy.
   * @return A new PlayerMoveEvent RecordBuilder
   */
  public static com.org.mars.avro.PlayerMoveEvent.Builder newBuilder(com.org.mars.avro.PlayerMoveEvent other) {
    if (other == null) {
      return new com.org.mars.avro.PlayerMoveEvent.Builder();
    } else {
      return new com.org.mars.avro.PlayerMoveEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for PlayerMoveEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PlayerMoveEvent>
    implements org.apache.avro.data.RecordBuilder<PlayerMoveEvent> {

    private com.org.mars.avro.PlayerState messageType;
    private long tick;
    private long worldTime;
    private com.org.mars.avro.Environment environment;
    private com.org.mars.avro.Environment.Builder environmentBuilder;
    private java.util.Map<java.lang.CharSequence,com.org.mars.avro.Player> players;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.org.mars.avro.PlayerMoveEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.messageType)) {
        this.messageType = data().deepCopy(fields()[0].schema(), other.messageType);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.tick)) {
        this.tick = data().deepCopy(fields()[1].schema(), other.tick);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.worldTime)) {
        this.worldTime = data().deepCopy(fields()[2].schema(), other.worldTime);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.environment)) {
        this.environment = data().deepCopy(fields()[3].schema(), other.environment);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (other.hasEnvironmentBuilder()) {
        this.environmentBuilder = com.org.mars.avro.Environment.newBuilder(other.getEnvironmentBuilder());
      }
      if (isValidValue(fields()[4], other.players)) {
        this.players = data().deepCopy(fields()[4].schema(), other.players);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing PlayerMoveEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.org.mars.avro.PlayerMoveEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.messageType)) {
        this.messageType = data().deepCopy(fields()[0].schema(), other.messageType);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.tick)) {
        this.tick = data().deepCopy(fields()[1].schema(), other.tick);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.worldTime)) {
        this.worldTime = data().deepCopy(fields()[2].schema(), other.worldTime);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.environment)) {
        this.environment = data().deepCopy(fields()[3].schema(), other.environment);
        fieldSetFlags()[3] = true;
      }
      this.environmentBuilder = null;
      if (isValidValue(fields()[4], other.players)) {
        this.players = data().deepCopy(fields()[4].schema(), other.players);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'messageType' field.
      * @return The value.
      */
    public com.org.mars.avro.PlayerState getMessageType() {
      return messageType;
    }


    /**
      * Sets the value of the 'messageType' field.
      * @param value The value of 'messageType'.
      * @return This builder.
      */
    public com.org.mars.avro.PlayerMoveEvent.Builder setMessageType(com.org.mars.avro.PlayerState value) {
      validate(fields()[0], value);
      this.messageType = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'messageType' field has been set.
      * @return True if the 'messageType' field has been set, false otherwise.
      */
    public boolean hasMessageType() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'messageType' field.
      * @return This builder.
      */
    public com.org.mars.avro.PlayerMoveEvent.Builder clearMessageType() {
      messageType = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'tick' field.
      * @return The value.
      */
    public long getTick() {
      return tick;
    }


    /**
      * Sets the value of the 'tick' field.
      * @param value The value of 'tick'.
      * @return This builder.
      */
    public com.org.mars.avro.PlayerMoveEvent.Builder setTick(long value) {
      validate(fields()[1], value);
      this.tick = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'tick' field has been set.
      * @return True if the 'tick' field has been set, false otherwise.
      */
    public boolean hasTick() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'tick' field.
      * @return This builder.
      */
    public com.org.mars.avro.PlayerMoveEvent.Builder clearTick() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'worldTime' field.
      * @return The value.
      */
    public long getWorldTime() {
      return worldTime;
    }


    /**
      * Sets the value of the 'worldTime' field.
      * @param value The value of 'worldTime'.
      * @return This builder.
      */
    public com.org.mars.avro.PlayerMoveEvent.Builder setWorldTime(long value) {
      validate(fields()[2], value);
      this.worldTime = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'worldTime' field has been set.
      * @return True if the 'worldTime' field has been set, false otherwise.
      */
    public boolean hasWorldTime() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'worldTime' field.
      * @return This builder.
      */
    public com.org.mars.avro.PlayerMoveEvent.Builder clearWorldTime() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'environment' field.
      * @return The value.
      */
    public com.org.mars.avro.Environment getEnvironment() {
      return environment;
    }


    /**
      * Sets the value of the 'environment' field.
      * @param value The value of 'environment'.
      * @return This builder.
      */
    public com.org.mars.avro.PlayerMoveEvent.Builder setEnvironment(com.org.mars.avro.Environment value) {
      validate(fields()[3], value);
      this.environmentBuilder = null;
      this.environment = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'environment' field has been set.
      * @return True if the 'environment' field has been set, false otherwise.
      */
    public boolean hasEnvironment() {
      return fieldSetFlags()[3];
    }

    /**
     * Gets the Builder instance for the 'environment' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.org.mars.avro.Environment.Builder getEnvironmentBuilder() {
      if (environmentBuilder == null) {
        if (hasEnvironment()) {
          setEnvironmentBuilder(com.org.mars.avro.Environment.newBuilder(environment));
        } else {
          setEnvironmentBuilder(com.org.mars.avro.Environment.newBuilder());
        }
      }
      return environmentBuilder;
    }

    /**
     * Sets the Builder instance for the 'environment' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.org.mars.avro.PlayerMoveEvent.Builder setEnvironmentBuilder(com.org.mars.avro.Environment.Builder value) {
      clearEnvironment();
      environmentBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'environment' field has an active Builder instance
     * @return True if the 'environment' field has an active Builder instance
     */
    public boolean hasEnvironmentBuilder() {
      return environmentBuilder != null;
    }

    /**
      * Clears the value of the 'environment' field.
      * @return This builder.
      */
    public com.org.mars.avro.PlayerMoveEvent.Builder clearEnvironment() {
      environment = null;
      environmentBuilder = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'players' field.
      * @return The value.
      */
    public java.util.Map<java.lang.CharSequence,com.org.mars.avro.Player> getPlayers() {
      return players;
    }


    /**
      * Sets the value of the 'players' field.
      * @param value The value of 'players'.
      * @return This builder.
      */
    public com.org.mars.avro.PlayerMoveEvent.Builder setPlayers(java.util.Map<java.lang.CharSequence,com.org.mars.avro.Player> value) {
      validate(fields()[4], value);
      this.players = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'players' field has been set.
      * @return True if the 'players' field has been set, false otherwise.
      */
    public boolean hasPlayers() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'players' field.
      * @return This builder.
      */
    public com.org.mars.avro.PlayerMoveEvent.Builder clearPlayers() {
      players = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PlayerMoveEvent build() {
      try {
        PlayerMoveEvent record = new PlayerMoveEvent();
        record.messageType = fieldSetFlags()[0] ? this.messageType : (com.org.mars.avro.PlayerState) defaultValue(fields()[0]);
        record.tick = fieldSetFlags()[1] ? this.tick : (java.lang.Long) defaultValue(fields()[1]);
        record.worldTime = fieldSetFlags()[2] ? this.worldTime : (java.lang.Long) defaultValue(fields()[2]);
        if (environmentBuilder != null) {
          try {
            record.environment = this.environmentBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("environment"));
            throw e;
          }
        } else {
          record.environment = fieldSetFlags()[3] ? this.environment : (com.org.mars.avro.Environment) defaultValue(fields()[3]);
        }
        record.players = fieldSetFlags()[4] ? this.players : (java.util.Map<java.lang.CharSequence,com.org.mars.avro.Player>) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PlayerMoveEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<PlayerMoveEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PlayerMoveEvent>
    READER$ = (org.apache.avro.io.DatumReader<PlayerMoveEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeEnum(this.messageType.ordinal());

    out.writeLong(this.tick);

    out.writeLong(this.worldTime);

    this.environment.customEncode(out);

    long size0 = this.players.size();
    out.writeMapStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.util.Map.Entry<java.lang.CharSequence, com.org.mars.avro.Player> e0: this.players.entrySet()) {
      actualSize0++;
      out.startItem();
      out.writeString(e0.getKey());
      com.org.mars.avro.Player v0 = e0.getValue();
      v0.customEncode(out);
    }
    out.writeMapEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Map-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.messageType = com.org.mars.avro.PlayerState.values()[in.readEnum()];

      this.tick = in.readLong();

      this.worldTime = in.readLong();

      if (this.environment == null) {
        this.environment = new com.org.mars.avro.Environment();
      }
      this.environment.customDecode(in);

      long size0 = in.readMapStart();
      java.util.Map<java.lang.CharSequence,com.org.mars.avro.Player> m0 = this.players; // Need fresh name due to limitation of macro system
      if (m0 == null) {
        m0 = new java.util.HashMap<java.lang.CharSequence,com.org.mars.avro.Player>((int)size0);
        this.players = m0;
      } else m0.clear();
      for ( ; 0 < size0; size0 = in.mapNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.CharSequence k0 = null;
          k0 = in.readString(k0 instanceof Utf8 ? (Utf8)k0 : null);
          com.org.mars.avro.Player v0 = null;
          if (v0 == null) {
            v0 = new com.org.mars.avro.Player();
          }
          v0.customDecode(in);
          m0.put(k0, v0);
        }
      }

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.messageType = com.org.mars.avro.PlayerState.values()[in.readEnum()];
          break;

        case 1:
          this.tick = in.readLong();
          break;

        case 2:
          this.worldTime = in.readLong();
          break;

        case 3:
          if (this.environment == null) {
            this.environment = new com.org.mars.avro.Environment();
          }
          this.environment.customDecode(in);
          break;

        case 4:
          long size0 = in.readMapStart();
          java.util.Map<java.lang.CharSequence,com.org.mars.avro.Player> m0 = this.players; // Need fresh name due to limitation of macro system
          if (m0 == null) {
            m0 = new java.util.HashMap<java.lang.CharSequence,com.org.mars.avro.Player>((int)size0);
            this.players = m0;
          } else m0.clear();
          for ( ; 0 < size0; size0 = in.mapNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.CharSequence k0 = null;
              k0 = in.readString(k0 instanceof Utf8 ? (Utf8)k0 : null);
              com.org.mars.avro.Player v0 = null;
              if (v0 == null) {
                v0 = new com.org.mars.avro.Player();
              }
              v0.customDecode(in);
              m0.put(k0, v0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










